"""Repository port protocols for the product domain."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from ariadne.product.domain.annotation import Annotation
from ariadne.product.domain.artifact import Artifact
from ariadne.product.domain.dataset_version import DatasetVersion
from ariadne.product.domain.execution import Execution
from ariadne.product.domain.graph_version import GraphVersion
from ariadne.product.domain.project import Project
from ariadne.product.domain.result import Result


@runtime_checkable
class ProjectRepository(Protocol):
    def add(self, project: Project) -> None: ...
    def get(self, project_id: str) -> Project | None: ...
    def update(self, project: Project) -> None: ...
    def list(self) -> list[Project]: ...


@runtime_checkable
class DatasetVersionRepository(Protocol):
    def add(self, dataset_version: DatasetVersion) -> None: ...
    def get(self, dataset_version_id: str) -> DatasetVersion | None: ...
    def list_by_project(self, project_id: str) -> list[DatasetVersion]: ...
    def exists_hash(self, project_id: str, dataset_key: str, content_hash: str) -> bool: ...


@runtime_checkable
class ExecutionRepository(Protocol):
    def add_many(self, executions: list[Execution]) -> None: ...
    def get(self, execution_id: str) -> Execution | None: ...
    def list_by_project(self, project_id: str) -> list[Execution]: ...
    def claim_next(
        self,
        worker_token: str,
        *,
        worker_id: str | None = None,
        lease_seconds: int = 1800,
    ) -> Execution | None: ...
    def renew_lease(self, execution_id: str, owner: str, lease_seconds: int = 1800) -> None: ...
    def update(self, execution: Execution, *, owner: str | None = None) -> None: ...
    def complete(self, execution: Execution, owner: str) -> None: ...


@runtime_checkable
class ResultRepository(Protocol):
    def add_many(self, results: list[Result]) -> None: ...
    def get(self, result_id: str) -> Result | None: ...
    def list_by_execution(self, execution_id: str) -> list[Result]: ...
    def get_many(self, result_ids: list[str]) -> list[Result]: ...


@runtime_checkable
class ArtifactRepository(Protocol):
    def add_many(self, artifacts: list[Artifact]) -> None: ...
    def get(self, artifact_id: str) -> Artifact | None: ...
    def list_by_execution(self, execution_id: str) -> list[Artifact]: ...
    def list_by_result(self, result_id: str) -> list[Artifact]: ...


@runtime_checkable
class GraphVersionRepository(Protocol):
    def add(self, graph_version: GraphVersion) -> None: ...
    def get(self, graph_version_id: str) -> GraphVersion | None: ...
    def list_by_project(self, project_id: str) -> list[GraphVersion]: ...
    def update(self, graph_version: GraphVersion) -> None: ...


@runtime_checkable
class AnnotationRepository(Protocol):
    def add(self, annotation: Annotation) -> None: ...
    def get(self, annotation_id: str) -> Annotation | None: ...
    def update(self, annotation: Annotation) -> None: ...
    def list_by_target(
        self,
        *,
        result_id: str | None = None,
        graph_version_id: str | None = None,
    ) -> list[Annotation]: ...
