const API="/api/v1";
const state={projects:[],project:null,datasets:[],executions:[],results:[],graphs:[],graphCandidates:[],graphCandidate:null,editingGraph:null,sourceGraph:null,pendingArchive:null};
const $=(selector)=>document.querySelector(selector);
const $$=(selector)=>[...document.querySelectorAll(selector)];

async function api(path,options={}){
  const response=await fetch(API+path,options);
  if(!response.ok){
    let body={};try{body=await response.json()}catch{}
    const error=body.error||{};
    const details=Array.isArray(error.details?.errors)?error.details.errors.map(item=>{
      const location=Array.isArray(item.loc)?item.loc.filter(value=>value!=='body').join('.'):'request';
      return `${location||'request'}: ${item.msg||'invalid value'}`;
    }).join('; '):'';
    const summary=error.code?`${error.code}: ${error.message}`:(error.message||`${response.status} ${response.statusText}`);
    throw new Error(details?`${summary} (${details})`:summary);
  }
  if(response.status===204)return null;
  return response.json();
}
let noticeTimer=null;
function notice(message){const el=$("#notice");el.textContent=message;el.classList.add("show");if(noticeTimer)clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>el.classList.remove("show"),5000)}
function list(value){return value.split(/[,\n]/).map(x=>x.trim()).filter(Boolean)}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function idempotencyKey(){
  if(typeof globalThis.crypto?.randomUUID==="function")return globalThis.crypto.randomUUID();
  if(typeof globalThis.crypto?.getRandomValues==="function"){
    const bytes=globalThis.crypto.getRandomValues(new Uint8Array(16));
    bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;
    const hex=[...bytes].map(value=>value.toString(16).padStart(2,"0"));
    return `${hex.slice(0,4).join("")}-${hex.slice(4,6).join("")}-${hex.slice(6,8).join("")}-${hex.slice(8,10).join("")}-${hex.slice(10).join("")}`;
  }
  // This key prevents duplicate commands; it is not used as a security token.
  return `web-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;
}

function enhanceTooltips(){
  $$('label[data-tooltip]').forEach((label,index)=>{
    if(label.querySelector(':scope > .tooltip-trigger'))return;
    const id=`field-tooltip-${index}`;
    const trigger=document.createElement('button');
    trigger.type='button';trigger.className='tooltip-trigger';trigger.textContent='?';
    trigger.setAttribute('aria-label','入力項目の説明');trigger.setAttribute('aria-describedby',id);
    const content=document.createElement('span');
    content.id=id;content.className='tooltip-content';content.setAttribute('role','tooltip');
    content.textContent=label.dataset.tooltip||'';
    label.prepend(content);label.prepend(trigger);
  });
}
enhanceTooltips();

$$('nav [data-workspace]').forEach(button=>button.onclick=async()=>{
  button.dataset.refreshStatus='pending';
  $$('nav button').forEach(x=>x.classList.remove('active'));button.classList.add('active');
  $$('.workspace').forEach(x=>x.classList.remove('active'));$('#'+button.dataset.workspace).classList.add('active');
  try{await refreshAll();button.dataset.refreshStatus='done'}catch(error){button.dataset.refreshStatus='failed';notice(error.message);throw error}
});

async function loadProjects(){
  const data=await api('/projects');state.projects=data.items;const select=$('#project-select');
  select.innerHTML='<option value="">Projectを選択</option>'+data.items.map(p=>`<option value="${p.project_id}">${escapeHtml(p.name)}</option>`).join('');
  if(state.project){select.value=state.project.project_id}
  $('#project-list').innerHTML=data.items.length?`<table><thead><tr><th>Name</th><th>Topic</th><th>Objective</th><th>Status</th><th></th></tr></thead><tbody>${data.items.map(p=>`<tr><td><button type="button" class="link-button" onclick="selectProject('${p.project_id}')">${escapeHtml(p.name)}</button></td><td>${escapeHtml(p.topic||'—')}</td><td>${escapeHtml(p.objective||'—')}</td><td><span class="status">${p.status}</span></td><td><button type="button" class="danger" onclick="requestArchive('${p.project_id}')">削除</button></td></tr>`).join('')}</tbody></table>`:'ACTIVE Projectはありません';
}
$('#new-project').onclick=()=>{$$('nav [data-workspace]')[0].click()};
$('#project-select').onchange=async event=>{state.project=event.target.value?await api(`/projects/${event.target.value}`):null;fillProject();await refreshAll()};
window.selectProject=async id=>{state.project=await api(`/projects/${id}`);fillProject();await loadProjects();$$('nav [data-workspace]').find(item=>item.dataset.workspace==='data').click()};
function fillProject(){const form=$('#project-form');for(const name of ['name','topic','objective','memo'])form.elements[name].value=state.project?.[name]||''}
$('#project-register-form').onsubmit=async event=>{event.preventDefault();try{state.project=await api('/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(event.target)))});event.target.reset();await loadProjects();$('#project-select').value=state.project.project_id;fillProject();notice('Projectを登録しました')}catch(error){notice(error.message)}};
$('#project-form').onsubmit=async event=>{event.preventDefault();if(!state.project)return notice('ACTIVE Projectを選択してください');try{const body=Object.fromEntries(new FormData(event.target));state.project=await api(`/projects/${state.project.project_id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await loadProjects();$('#project-select').value=state.project.project_id;notice('Project metadataを更新しました')}catch(error){notice(error.message)}};
window.requestArchive=id=>{state.pendingArchive=id;$('#archive-modal').showModal()};
$('#confirm-archive').onclick=async()=>{if(!state.pendingArchive)return;try{await api(`/projects/${state.pendingArchive}`,{method:'DELETE'});if(state.project?.project_id===state.pendingArchive){state.project=null;fillProject();state.datasets=[];state.executions=[];state.results=[];state.graphs=[];state.graphCandidates=[]}state.pendingArchive=null;$('#archive-modal').close();await loadProjects();$('#project-select').value='';$$('nav [data-workspace]')[0].click();notice('ProjectをARCHIVEDへ変更しました。既存Lineageは保持されます')}catch(error){notice(error.message)}};

$('#dataset-form').onsubmit=async event=>{event.preventDefault();if(!state.project)return notice('Projectを選択してください');try{const form=new FormData(event.target);await api(`/projects/${state.project.project_id}/dataset-versions`,{method:'POST',headers:{'Idempotency-Key':idempotencyKey()},body:form});event.target.reset();await loadDatasets();notice('Dataset Versionを登録しました')}catch(error){notice(error.message)}};
async function loadDatasets(){
  if(!state.project){state.datasets=[];return}
  state.datasets=(await api(`/projects/${state.project.project_id}/dataset-versions`)).items;
  $('#datasets').innerHTML=state.datasets.length?`<table><thead><tr><th>Name</th><th>Version</th><th>Schema</th><th>Rows × Columns</th><th>Hash</th><th></th></tr></thead><tbody>${state.datasets.map(d=>`<tr><td>${escapeHtml(d.name)}</td><td>${escapeHtml(d.version_label)}</td><td>${escapeHtml(Object.entries(d.schema).map(([name,type])=>`${name}:${type}`).join(', '))}</td><td>${d.row_count} × ${d.column_count}</td><td>${d.content_hash.slice(0,12)}</td><td><button onclick="preview('${d.dataset_version_id}')">Preview</button></td></tr>`).join('')}</tbody></table>`:'Datasetはありません';
  $$('.datasets-select').forEach(select=>select.innerHTML='<option value="">選択</option>'+state.datasets.map(d=>`<option value="${d.dataset_version_id}">${escapeHtml(d.name)} / ${escapeHtml(d.version_label)}</option>`).join(''));
}
window.preview=async id=>{try{const p=await api(`/dataset-versions/${id}/preview?limit=10`);$('#preview').innerHTML=`<h3>Preview</h3><table><thead><tr>${p.columns.map(c=>`<th>${escapeHtml(c)}</th>`).join('')}</tr></thead><tbody>${p.rows.map(row=>`<tr>${p.columns.map(c=>`<td>${escapeHtml(row[c])}</td>`).join('')}</tr>`).join('')}</tbody></table>`}catch(error){notice(error.message)}};

function selectedDiscoveryDataset(){const id=$('#discovery-form').elements.dataset_version_id.value;return state.datasets.find(item=>item.dataset_version_id===id)}
$('#open-feature-selector').onclick=()=>{const dataset=selectedDiscoveryDataset();if(!dataset)return notice('Datasetを先に選択してください');const current=new Set(list($('#discovery-form').elements.features.value));$('#feature-options').innerHTML=Object.keys(dataset.schema||{}).map(name=>`<label class="check-row"><input type="checkbox" value="${escapeHtml(name)}" ${current.has(name)?'checked':''}> <span>${escapeHtml(name)}</span><small>${escapeHtml(dataset.schema[name])}</small></label>`).join('');$('#feature-modal').showModal()};
$('#confirm-features').onclick=()=>{const dataset=selectedDiscoveryDataset();if(!dataset)return;const checked=new Set($$('#feature-options input:checked').map(item=>item.value));const ordered=Object.keys(dataset.schema||{}).filter(name=>checked.has(name));$('#discovery-form').elements.features.value=ordered.join(', ');syncOutcomeOptions();$('#feature-modal').close()};
function syncOutcomeOptions(){const features=list($('#discovery-form').elements.features.value),select=$('#discovery-outcome'),old=select.value;select.innerHTML='<option value="">Outcomeを選択</option>'+features.map(name=>`<option value="${escapeHtml(name)}">${escapeHtml(name)}</option>`).join('');select.value=features.includes(old)?old:''}
$('#discovery-form').elements.dataset_version_id.onchange=()=>{$('#discovery-form').elements.features.value='';syncOutcomeOptions()};

function discoveryRequest(form){
  const datasetId=String(form.get('dataset_version_id')||'');
  const dataset=state.datasets.find(item=>item.dataset_version_id===datasetId);
  if(!dataset)throw new Error('Datasetを選択してください');

  const features=list(String(form.get('features')||''));
  if(!features.length)throw new Error('Feature columnsを1件以上指定してください');
  if(new Set(features).size!==features.length)throw new Error('Feature columnsに重複があります');
  const knownColumns=new Set(Object.keys(dataset.schema||{}));
  const unknown=features.filter(name=>!knownColumns.has(name));
  if(unknown.length)throw new Error(`Datasetに存在しないFeature columns: ${unknown.join(', ')}`);
  const outcome=String(form.get('designated_outcome_node')||'');
  if(!outcome||!features.includes(outcome))throw new Error('OutcomeをFeature columnsから1件選択してください');

  const algorithms=form.getAll('algorithms').map(String);
  if(!algorithms.length)throw new Error('Algorithmを1件以上選択してください');
  const variants=[];
  if(algorithms.includes('pc')){
    const alphaTokens=list(String(form.get('alpha')||''));
    if(!alphaTokens.length)throw new Error('PCを選択した場合はalphaを1件以上指定してください');
    const invalid=alphaTokens.filter(token=>{
      const value=Number(token);return !Number.isFinite(value)||value<=0||value>=1;
    });
    if(invalid.length)throw new Error(`PC alphaは0より大きく1より小さい数値にしてください: ${invalid.join(', ')}`);
    for(const token of alphaTokens)variants.push({algorithm_or_estimator:'pc',parameters:{alpha:Number(token)},random_seed:42});
  }
  if(algorithms.includes('ges'))variants.push({algorithm_or_estimator:'ges',parameters:{},random_seed:42});
  if(variants.length>20)throw new Error(`Executionは一度に20件までです（現在${variants.length}件）`);

  return {operation:'DISCOVERY',dataset_version_id:datasetId,input_graph_version_id:null,input_result_id:null,objective:form.get('objective')||null,rationale:form.get('rationale')||null,analysis_spec:{schema_version:'causal-analysis-spec/2',analysis_mode:'EXPLORATORY',research_context:{problem_statement:null,research_question:null,significance:null,hypothesis:null},causal_question:{},causal_design:{adjustment_set:[],assumptions:[]},operation_spec:{feature_columns:features,designated_outcome_node:outcome,constraints:{required_edges:[],forbidden_edges:[],temporal_tiers:[]},expected_graph_type:null},validation_override:null},variants,code_version:'web-enh-e2',runtime_versions:{client:'web'}};
}
$('#discovery-form').onsubmit=async event=>{
  event.preventDefault();
  if(!state.project)return notice('Projectを選択してください');
  try{
    const body=discoveryRequest(new FormData(event.target));
    await api(`/projects/${state.project.project_id}/execution-batches`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey()},body:JSON.stringify(body)});
    notice(`${body.variants.length}件のDiscoveryを受け付けました`);
    await loadExecutions();
  }catch(error){notice(error.message)}
};
async function loadExecutions(){if(!state.project){state.executions=[];state.results=[];return}state.executions=(await api(`/projects/${state.project.project_id}/executions`)).items;state.results=[];for(const execution of state.executions){if(execution.status==='SUCCEEDED'){const values=(await api(`/executions/${execution.execution_id}/results`)).items;values.forEach(value=>value.execution=execution);state.results.push(...values)}}const bases=$('#base-executions');if(bases)bases.innerHTML='<option value="">新規分析</option>'+state.executions.filter(e=>e.operation==='ESTIMATION').map(e=>`<option value="${e.execution_id}">${escapeHtml(e.algorithm_or_estimator)} / ${e.execution_id.slice(0,8)}</option>`).join('');renderDiscovery();renderInference();renderResultOptions()}
function resultRows(operation,target){const values=state.results.filter(r=>r.execution.operation===operation);target.innerHTML=values.length?`<table><thead><tr><th></th><th>Method</th><th>Status</th><th>Summary</th></tr></thead><tbody>${values.map(r=>`<tr><td><input type="checkbox" value="${r.result_id}"></td><td>${escapeHtml(r.execution.algorithm_or_estimator)}</td><td class="${r.scientific_status}">${r.scientific_status}</td><td>${escapeHtml(JSON.stringify(r.summary))}</td></tr>`).join('')}</tbody></table>`:'完了Resultはありません';return values}
function renderDiscovery(){resultRows('DISCOVERY',$('#discovery-results'));renderGraphCandidates()}
async function refreshExecutions(button){button.dataset.refreshStatus='pending';try{await loadExecutions();button.dataset.refreshStatus='done'}catch(error){button.dataset.refreshStatus='failed';notice(error.message);throw error}}
$('#refresh-discovery').onclick=async event=>{const button=event.currentTarget;button.dataset.refreshStatus='pending';try{await loadExecutions();await loadGraphs();button.dataset.refreshStatus='done'}catch(error){button.dataset.refreshStatus='failed';notice(error.message);throw error}};
$('#compare-discovery').onclick=compareGraphCandidates;
async function compareChecked(container,output,minimum=2){const ids=$$(`${container} input:checked`).map(x=>x.value);if(ids.length<minimum)return notice(`${minimum}件以上選択してください`);try{$(output).textContent=JSON.stringify(await api('/comparisons/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:state.project.project_id,result_ids:ids})}),null,2)}catch(error){notice(error.message)}}
$('#graph-source').onchange=()=>{const result=state.results.find(r=>r.result_id===$('#graph-source').value);if(result)$('#graph-parent').value='';state.sourceGraph=result?structuredClone(result.payload):null;state.editingGraph=result?structuredClone(result.payload):null;renderGraphEditor()};
$('#graph-parent').onchange=()=>{const graph=state.graphs.find(g=>g.graph_version_id===$('#graph-parent').value);if(graph)$('#graph-source').value='';state.sourceGraph=graph?structuredClone(graph.graph):null;state.editingGraph=graph?structuredClone(graph.graph):null;renderGraphEditor()};
function renderGraphEditor(){const graph=state.editingGraph,editable=Boolean(state.graphCandidate?.allowed_actions?.can_edit)||state.graphCandidate?.candidate_kind==='DISCOVERY_RESULT'||state.graphCandidate?.fixed;$('#graph-editor').innerHTML=!graph?'Graph Candidateを選択してください':`<p>Type: <b>${graph.graph_type}</b> / Nodes: ${graph.nodes.length}</p>${graph.edges.map((edge,index)=>`<div class="edge"><span>${escapeHtml(edge.source)} ${edge.endpoint_source} — ${edge.endpoint_target} ${escapeHtml(edge.target)}</span>${editable?`<button type="button" onclick="removeEdge(${index})">削除</button>`:''}</div>`).join('')}`;renderGraphVisual(graph,$('#graph-visual'),state.graphCandidate?.designated_outcome_node)}
window.removeEdge=index=>{state.editingGraph.edges.splice(index,1);renderGraphEditor()};
$('#add-edge').onclick=()=>{if(!state.editingGraph)return;const source=$('#edge-source').value.trim(),target=$('#edge-target').value.trim();if(!state.editingGraph.nodes.includes(source)||!state.editingGraph.nodes.includes(target)||source===target)return notice('既存の異なるnodeを指定してください');state.editingGraph.edges.push({source,target,endpoint_source:'TAIL',endpoint_target:'ARROW'});renderGraphEditor()};
$('#save-graph').onclick=async()=>{const candidate=state.graphCandidate,rationale=$('#graph-rationale').value.trim();if(!candidate||!state.editingGraph)return notice('Graph Candidateを選択してください');if(!rationale)return notice('選定・編集理由を入力してください');try{let graph;if(candidate.candidate_kind==='GRAPH_VERSION'&&candidate.version_status==='DRAFT'){graph=await api(`/projects/${state.project.project_id}/graph-versions/${candidate.graph_version_id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({graph:state.editingGraph,designated_outcome_node:$('#graph-outcome').value.trim()||null,edit_rationale:rationale,expected_content_hash:candidate.summary?.content_hash||null})})}else{graph=await api(`/projects/${state.project.project_id}/graph-edit-drafts`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey()},body:JSON.stringify({base_candidate_kind:candidate.candidate_kind,base_candidate_id:candidate.candidate_id,change_kind:$('#graph-transform').value,name:`Edited graph ${new Date().toISOString()}`,edit_rationale:rationale})});if(JSON.stringify(state.editingGraph)!==JSON.stringify(state.sourceGraph)||$('#graph-outcome').value.trim()!==String(graph.designated_outcome_node||'')){graph=await api(`/projects/${state.project.project_id}/graph-versions/${graph.graph_version_id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({graph:state.editingGraph,designated_outcome_node:$('#graph-outcome').value.trim()||null,edit_rationale:rationale})})}}await loadGraphs();await inspectCandidate('GRAPH_VERSION',graph.graph_version_id);notice('元Graphを保持し、編集内容をDRAFTへ保存しました')}catch(error){notice(error.message)}};
$('#fix-graph').onclick=async()=>{const candidate=state.graphCandidate;if(candidate?.candidate_kind!=='GRAPH_VERSION'||candidate.version_status!=='DRAFT')return notice('FIXできるのはDRAFT Graph Versionだけです');try{const graph=await api(`/projects/${state.project.project_id}/graph-versions/${candidate.graph_version_id}/fix`,{method:'POST'});await loadGraphs();await inspectCandidate('GRAPH_VERSION',graph.graph_version_id);notice('Graph VersionをFIXEDにしました。以後は直接更新できません')}catch(error){notice(error.message)}};
$('#adopt-graph').onclick=async()=>{const candidate=state.graphCandidate,rationale=$('#graph-rationale').value.trim();if(candidate?.candidate_kind!=='DISCOVERY_RESULT')return notice('Algorithm Outputだけを直接採用できます');if(!rationale)return notice('選定理由を入力してください');try{const graph=await api(`/projects/${state.project.project_id}/graph-versions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source_result_id:candidate.candidate_id,parent_graph_version_id:null,graph_origin:'DISCOVERED',name:`Selected graph ${new Date().toISOString()}`,graph_type:candidate.graph_type,graph:candidate.graph,designated_outcome_node:candidate.designated_outcome_node,provenance:{algorithm_output:true,selection_rationale:rationale},edit_rationale:rationale,fix_immediately:true})});await loadGraphs();await inspectCandidate('GRAPH_VERSION',graph.graph_version_id);notice('Algorithm Outputを変更せずDISCOVERED FIXED Versionとして採用しました')}catch(error){notice(error.message)}};
$('#save-direct-graph').onclick=async()=>{if(!state.project)return notice('Projectを選択してください');const origin=$('#direct-graph-origin').value,note=$('#direct-graph-note').value.trim(),name=$('#direct-graph-name').value.trim(),outcome=$('#direct-graph-outcome').value.trim();if(!note||!name||!outcome)return notice('Name、Designated Outcome、Source / import noteを入力してください');let graph;try{graph=JSON.parse($('#direct-graph-json').value)}catch{return notice('Graph JSONが不正です')}try{await api(`/projects/${state.project.project_id}/graph-versions`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey()},body:JSON.stringify({source_result_id:null,parent_graph_version_id:null,graph_origin:origin,name,graph_type:graph.graph_type,graph,designated_outcome_node:outcome,provenance:{source_note:note},edit_rationale:null,fix_immediately:false})});await loadGraphs();notice('Direct GraphをDRAFT Versionとして保存しました')}catch(error){notice(error.message)}};

function renderGraphCandidates(){const target=$('#graph-candidates');if(!target)return;target.innerHTML=state.graphCandidates.length?`<table><thead><tr><th></th><th>Kind / FIXED</th><th>Source / Parent</th><th>Type / Origin</th><th>Status</th><th>Outcome</th><th>Summary</th><th>操作</th></tr></thead><tbody>${state.graphCandidates.map(c=>`<tr><td><input class="candidate-check" type="checkbox" data-kind="${c.candidate_kind}" value="${c.candidate_id}"></td><td>${c.candidate_kind}<br><span class="status">${c.fixed?'FIXED':'—'}</span></td><td>${escapeHtml(c.parent_graph_version_id||c.source_result_id||'root')}</td><td>${c.graph_type}<br>${c.graph_origin}</td><td>${escapeHtml(c.version_status||c.scientific_status||'—')}</td><td>${escapeHtml(c.designated_outcome_node||'未指定')}</td><td>${c.summary.node_count} nodes / ${c.summary.edge_count} edges<br>${escapeHtml(c.warnings.join?.(', ')||'')}</td><td><button type="button" onclick="inspectCandidate('${c.candidate_kind}','${c.candidate_id}')">グラフを確認/編集する</button></td></tr>`).join('')}</tbody></table>`:'Graph Candidateはありません';$$('.candidate-check').forEach(item=>item.onchange=()=>{$('#compare-discovery').disabled=$$('.candidate-check:checked').length<2})}
window.inspectCandidate=inspectCandidate;
async function inspectCandidate(kind,id){try{const candidate=await api(`/projects/${state.project.project_id}/graph-candidates/${kind}/${id}`);state.graphCandidate=candidate;state.sourceGraph=structuredClone(candidate.graph);state.editingGraph=structuredClone(candidate.graph);$('#graph-meta').innerHTML=`<div class="badge-row"><span class="status">${candidate.graph_type}</span><span class="status">${candidate.graph_origin}</span><span class="status">${candidate.version_status||candidate.scientific_status}</span></div><p>Source: ${escapeHtml(candidate.source_result_id||'—')} / Parent: ${escapeHtml(candidate.parent_graph_version_id||'—')}</p><p>Outcome: ${escapeHtml(candidate.designated_outcome_node||'未指定')}</p>`;$('#graph-outcome').value=candidate.designated_outcome_node||'';$('#graph-rationale').value=candidate.summary.edit_rationale||'';$('#adopt-graph').hidden=candidate.candidate_kind!=='DISCOVERY_RESULT';$('#save-graph').disabled=!(candidate.allowed_actions.can_edit||candidate.allowed_actions.can_create_child);$('#fix-graph').disabled=!candidate.allowed_actions.can_fix;$('#add-edge').disabled=!(candidate.allowed_actions.can_edit||candidate.allowed_actions.can_create_child);$('#save-graph').textContent=candidate.allowed_actions.can_edit?'DRAFTを更新':'子DRAFTを作成';renderGraphEditor();$('#graph-modal').showModal()}catch(error){notice(error.message)}}
$('#close-graph-modal').onclick=()=>$('#graph-modal').close();
async function compareGraphCandidates(){const refs=$$('.candidate-check:checked').map(item=>({candidate_kind:item.dataset.kind,candidate_id:item.value}));if(refs.length<2)return notice('2件以上選択してください');try{const comparison=await api(`/projects/${state.project.project_id}/graph-candidate-comparisons/query`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({candidate_refs:refs})});$('#comparison-tabs').innerHTML=comparison.candidates.map((candidate,index)=>`<button type="button" data-index="${index}">${escapeHtml(candidate.summary.name||candidate.candidate_id.slice(0,8))}</button>`).join('');const show=index=>{const candidate=comparison.candidates[index];renderGraphVisual(candidate.graph,$('#comparison-graph'),candidate.designated_outcome_node);$('#comparison-summary').innerHTML=`<p><b>${candidate.graph_type}</b> / ${candidate.graph_origin} / ${candidate.summary.node_count} nodes / ${candidate.summary.edge_count} edges / Outcome: ${escapeHtml(candidate.designated_outcome_node||'未指定')}</p><h3>Compatibility</h3><p>${comparison.compatibility.compatible?'比較可能':`比較不能: ${escapeHtml(comparison.compatibility.reasons.join(', '))}`}</p><h3>Structure diff</h3>${comparison.compatibility.compatible?`<pre>${escapeHtml(JSON.stringify(comparison.differences,null,2))}</pre>`:'個別タブのGraph表示は利用できます。'}`};$$('#comparison-tabs button').forEach(button=>button.onclick=()=>show(Number(button.dataset.index)));show(0);$('#graph-comparison-modal').showModal()}catch(error){notice(error.message)}}
$('#close-comparison-modal').onclick=()=>$('#graph-comparison-modal').close();
function renderGraphVisual(graph,target,outcome){if(!graph){target.innerHTML='Graphはありません';return}const nodes=[...graph.nodes].sort((a,b)=>a===outcome?1:b===outcome?-1:a.localeCompare(b)),columns=Math.min(6,Math.max(1,nodes.length)),rows=Math.max(1,Math.ceil(nodes.length/columns)),width=Math.max(480,columns*140),height=rows*180+100,positions=new Map(nodes.map((node,index)=>{const row=Math.floor(index/columns),column=node===outcome?columns-1:index%columns;return [node,{x:70+column*(width-140)/Math.max(1,columns-1),y:80+row*180+(column%2)*90}]}));target.innerHTML=`<svg class="graph-svg" width="100%" viewBox="0 0 ${width} ${height}" preserveAspectRatio="xMidYMid meet" role="img" aria-label="${escapeHtml(graph.graph_type)} graph">${graph.edges.map(edge=>{const a=positions.get(edge.source),b=positions.get(edge.target);return a&&b?`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" class="graph-edge"/><text x="${(a.x+b.x)/2}" y="${(a.y+b.y)/2-5}" class="edge-label">${edge.endpoint_source}→${edge.endpoint_target}</text>`:''}).join('')}${nodes.map(node=>{const p=positions.get(node);return `<g class="graph-node ${node===outcome?'outcome':''}"><circle cx="${p.x}" cy="${p.y}" r="32"/><text x="${p.x}" y="${p.y+4}">${escapeHtml(node)}</text></g>`}).join('')}</svg>`}

async function loadGraphs(){if(!state.project){state.graphs=[];state.graphCandidates=[];renderGraphCandidates();return}const [graphs,candidates]=await Promise.all([api(`/projects/${state.project.project_id}/graph-versions`),api(`/projects/${state.project.project_id}/graph-candidates`)]);state.graphs=graphs.items;state.graphCandidates=candidates.items;const fixed=state.graphs.filter(g=>g.status==='FIXED'&&g.designated_outcome_node);$('#fixed-graphs').innerHTML='<option value="">選択</option>'+fixed.map(g=>`<option value="${g.graph_version_id}">${escapeHtml(g.name)} / ${g.graph_origin} / ${escapeHtml(g.designated_outcome_node)}</option>`).join('');$('#graph-parent').innerHTML='<option value="">選択</option>'+fixed.map(g=>`<option value="${g.graph_version_id}">${escapeHtml(g.name)} / ${g.graph_origin}</option>`).join('');renderGraphCandidates()}
function selectedInferenceGraph(){return state.graphs.find(graph=>graph.graph_version_id===$('#fixed-graphs').value)}
$('#fixed-graphs').onchange=()=>{const graph=selectedInferenceGraph(),outcome=graph?.designated_outcome_node;$('#inference-outcome').textContent=outcome||'Outcome未指定のため使用できません';$('#run-identification').disabled=!outcome;$('#inference-form').dispatchEvent(new Event('input',{bubbles:true}))};
$('#inference-form').oninput=event=>{const f=new FormData(event.currentTarget),strategy=f.get('strategy'),difference=$('#inference-form input[value="difference_in_means"]'),outcome=selectedInferenceGraph()?.designated_outcome_node;difference.disabled=strategy!=='RANDOMIZED';if(difference.disabled)difference.checked=false;const compatible=strategy==='RANDOMIZED'?'difference_in_means, ols, ipw, aipw':'ols, ipw, aipw';$('#preflight').textContent=`Preflight: treatment=${f.get('treatment')||'—'}, outcome=${outcome||'Graphで指定が必要'}, adjustment=[${list(f.get('adjustment')).join(', ')}], FIXED graph=${f.get('graph_version_id')?'selected':'required'}, compatible estimators=${compatible}`};
function inferenceSpec(f,operation_spec,override=null){const outcome=selectedInferenceGraph()?.designated_outcome_node;return {schema_version:'causal-analysis-spec/2',analysis_mode:f.get('analysis_mode')||'EXPLORATORY',research_context:{problem_statement:null,research_question:null,significance:null,hypothesis:null},causal_question:{population:f.get('population'),treatment:f.get('treatment'),comparator:f.get('comparator'),outcome,analysis_unit:f.get('analysis_unit'),treatment_time:f.get('treatment_time'),outcome_window:f.get('outcome_window'),estimand:f.get('estimand'),decision_use:null},causal_design:{assignment_assumption:null,time_zero:f.get('treatment_time'),eligibility_criteria:[],identification_strategy:f.get('strategy'),adjustment_set:list(f.get('adjustment')),assumptions:list(f.get('assumptions'))},operation_spec,validation_override:override}}
$('#run-identification').onclick=async()=>{const form=$('#inference-form'),f=new FormData(form);try{await api(`/projects/${state.project.project_id}/execution-batches`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey()},body:JSON.stringify({operation:'IDENTIFICATION',dataset_version_id:f.get('dataset_version_id'),input_graph_version_id:f.get('graph_version_id'),input_result_id:null,objective:'Identify causal effect',rationale:'Identification-first gate',analysis_spec:inferenceSpec(f,{allow_partial_identification:false}),variants:[{algorithm_or_estimator:'GRAPHICAL_IDENTIFICATION',parameters:{},random_seed:42}],code_version:'web-enh-e1',runtime_versions:{client:'web'}})});notice('Identificationを受け付けました');await loadExecutions()}catch(error){notice(error.message)}};
$('#inference-form').onsubmit=async event=>{event.preventDefault();if(!state.project)return notice('Projectを選択してください');const f=new FormData(event.target),estimators=f.getAll('estimators'),reason=String(f.get('override_reason')||'').trim(),override=reason?{reason,actor:'web-user',warning_codes:['ELIGIBILITY_WARN']}:null,base=String(f.get('base_execution_id')||'')||null,changeReason=String(f.get('change_reason')||'').trim()||null;try{const response=await api(`/projects/${state.project.project_id}/execution-batches`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey()},body:JSON.stringify({operation:'ESTIMATION',dataset_version_id:f.get('dataset_version_id'),input_graph_version_id:f.get('graph_version_id'),input_result_id:f.get('identification_result_id'),objective:'Estimate binary treatment effect',rationale:'Compare estimator sensitivity',analysis_spec:inferenceSpec(f,{inference_options:{}},override),variants:estimators.map(x=>({algorithm_or_estimator:x,parameters:{},random_seed:42})),code_version:'web-enh-e1',runtime_versions:{client:'web'},base_execution_id:base,change_reason:changeReason})});const warnings=response.executions.flatMap(x=>x.scientific_warnings||[]);$('#scientific-warnings').textContent=warnings.map(x=>`${x.warning_code}: ${x.message}`).join('\n');notice(warnings.length?`${estimators.length}件を警告付きで受け付けました`:`${estimators.length}件のEstimationを受け付けました`);await loadExecutions()}catch(error){notice(error.message)}};
function renderInference(){const ids=state.results.filter(r=>r.result_type==='IDENTIFICATION_RESULT');$('#identification-results').innerHTML='<option value="">選択</option>'+ids.map(r=>`<option value="${r.result_id}">${r.scientific_status} / ${r.result_id.slice(0,8)}</option>`).join('');$('#identification-panel').innerHTML=state.results.filter(r=>['IDENTIFICATION_RESULT','DATA_ELIGIBILITY_RESULT'].includes(r.result_type)).map(r=>`<p><b>${r.result_type}</b> <span class="${r.scientific_status}">${r.scientific_status}</span> ${escapeHtml(JSON.stringify({summary:r.summary,inferred_types:r.payload?.inferred_types,checks:r.payload?.checks,warnings:r.warnings}))}</p>`).join('')||'Resultはありません';resultRows('ESTIMATION',$('#inference-results'));const effects=state.results.filter(r=>r.result_type==='TREATMENT_EFFECT_RESULT');$$('.effect-results').forEach(select=>select.innerHTML='<option value="">選択</option>'+effects.map(r=>`<option value="${r.result_id}">${r.scientific_status} / ${r.result_id.slice(0,8)}</option>`).join(''))}
$('#refresh-inference').onclick=event=>refreshExecutions(event.currentTarget);$('#compare-inference').onclick=()=>compareChecked('#inference-results','#inference-comparison',2);

function followupSpec(operation_spec){return {schema_version:'causal-analysis-spec/2',analysis_mode:'EXPLORATORY',research_context:{},causal_question:{},causal_design:{adjustment_set:[],assumptions:[]},operation_spec,validation_override:null}}
$('#refutation-form').onsubmit=async event=>{event.preventDefault();const f=new FormData(event.target),base=state.results.find(r=>r.result_id===f.get('result_id'));if(!base)return notice('Treatment Effect Resultを選択してください');const method=f.get('method'),operation_spec=method==='PLACEBO_TREATMENT'?{method,repetitions:Number(f.get('repetitions'))}:{method,subset_fraction:Number(f.get('subset_fraction'))};try{await api(`/projects/${state.project.project_id}/execution-batches`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey()},body:JSON.stringify({operation:'REFUTATION',dataset_version_id:base.execution.dataset_version_id,input_graph_version_id:base.execution.input_graph_version_id,input_result_id:base.result_id,objective:'Refute treatment effect',rationale:'ENH-E1 minimum refutation',analysis_spec:followupSpec(operation_spec),variants:[{algorithm_or_estimator:method,parameters:{},random_seed:42}],code_version:'web-enh-e1',runtime_versions:{client:'web'}})});notice('Refutationを受け付けました')}catch(error){notice(error.message)}};
$('#sensitivity-form').onsubmit=async event=>{event.preventDefault();const f=new FormData(event.target),base=state.results.find(r=>r.result_id===f.get('result_id'));if(!base)return notice('Treatment Effect Resultを選択してください');const dimension=f.get('dimension'),operation_spec=dimension==='PROPENSITY_CLIPPING'?{dimension,values:list(f.get('values')).map(Number)}:{dimension,adjustment_sets:String(f.get('adjustment_sets')||'').split(';').filter(Boolean).map(list)};try{await api(`/projects/${state.project.project_id}/execution-batches`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey()},body:JSON.stringify({operation:'SENSITIVITY',dataset_version_id:base.execution.dataset_version_id,input_graph_version_id:base.execution.input_graph_version_id,input_result_id:base.result_id,objective:'Assess sensitivity',rationale:'ENH-E1 minimum sensitivity',analysis_spec:followupSpec(operation_spec),variants:[{algorithm_or_estimator:dimension,parameters:{},random_seed:42}],code_version:'web-enh-e1',runtime_versions:{client:'web'}})});notice('Sensitivityを受け付けました')}catch(error){notice(error.message)}};

function renderResultOptions(){const types=[...new Set(state.results.map(r=>r.result_type))].sort(),statuses=[...new Set(state.results.map(r=>r.scientific_status))].sort(),type=$('#result-type-filter').value,status=$('#result-status-filter').value;$('#result-type-filter').innerHTML='<option value="">すべて</option>'+types.map(value=>`<option ${value===type?'selected':''}>${value}</option>`).join('');$('#result-status-filter').innerHTML='<option value="">すべて</option>'+statuses.map(value=>`<option ${value===status?'selected':''}>${value}</option>`).join('');const values=state.results.filter(r=>(!type||r.result_type===type)&&(!status||r.scientific_status===status));$('#result-select').innerHTML='<option value="">選択</option>'+values.map(r=>`<option value="${r.result_id}">${r.result_type} / ${r.execution.algorithm_or_estimator} / ${r.scientific_status}</option>`).join('')}
$('#result-type-filter').onchange=renderResultOptions;
$('#result-status-filter').onchange=renderResultOptions;
$('#load-result').onclick=async()=>{const id=$('#result-select').value;if(!id)return;try{const result=await api(`/results/${id}`),lineage=await api(`/results/${id}/lineage`);$('#result-detail').innerHTML=`<h2>${result.result_type}</h2><p class="status ${result.scientific_status}">${result.scientific_status}</p><pre>${escapeHtml(JSON.stringify({summary:result.summary,diagnostics:result.diagnostics,warnings:result.warnings},null,2))}</pre><button id="export-result">Export JSON</button>`;$('#export-result').onclick=async()=>{try{const manifest=await api(`/results/${id}/export`,{method:'POST'}),blob=new Blob([JSON.stringify(manifest,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`ariadne-result-${id}.json`;link.click();URL.revokeObjectURL(url)}catch(error){notice(error.message)}};const artifactNodes=lineage.nodes.filter(n=>n.node_type==='Artifact');$('#artifacts').innerHTML='<h2>Artifacts</h2>'+artifactNodes.map(n=>`<a href="${API}/artifacts/${n.entity_id}/download">${escapeHtml(n.label)} download</a>`).join('<br>');$('#lineage').textContent=JSON.stringify(lineage,null,2)}catch(error){notice(error.message)}};
$('#annotation-form').onsubmit=async event=>{event.preventDefault();const result=$('#result-select').value;if(!result)return notice('Resultを選択してください');const f=new FormData(event.target);try{await api(`/projects/${state.project.project_id}/annotations`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target_result_id:result,target_graph_version_id:null,statement:f.get('statement'),rationale:f.get('rationale')||null,assumptions:list(f.get('assumptions')),limitations:list(f.get('limitations'))})});event.target.reset();notice('Annotationを記録しました')}catch(error){notice(error.message)}};

async function refreshAll(){if(!state.project)return;await Promise.all([loadDatasets(),loadGraphs(),loadExecutions()])}
// ENH-E1 contract references retained for traceability after the modal migration:
// target_graph_version_id:graph.graph_version_id
// parent_graph_version_id:parent||null
// origin=parent?$('#graph-transform').value:'DISCOVERED'
(async()=>{try{await fetch('/health/ready').then(r=>{if(!r.ok)throw Error();return r.json()});$('#health').textContent='API READY';await loadProjects()}catch{$('#health').textContent='API UNAVAILABLE'}})();
