FROM nginx:1.27-alpine

COPY frontend/ /usr/share/nginx/html/
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf

RUN find /usr/share/nginx/html -type d -exec chmod 0755 {} + \
 && find /usr/share/nginx/html -type f -exec chmod 0644 {} + \
 && chmod 0644 /etc/nginx/conf.d/default.conf
