FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_LINK_MODE=copy \
    UV_NO_CACHE=1

RUN pip install --no-cache-dir uv==0.8.3
WORKDIR /app
COPY pyproject.toml uv.lock README.md ./
RUN uv sync --frozen --dev --no-cache
COPY src ./src
COPY alembic_product.ini ./
COPY product_migrations ./product_migrations
COPY tests ./tests
COPY scripts ./scripts

ENV PATH="/app/.venv/bin:${PATH}" \
    PYTHONPATH=/app/src
CMD ["/app/scripts/test/run_product_postgres_tests_in_container.sh"]
