"""Enumerated value sets for the product domain."""

from __future__ import annotations

from enum import Enum


class ProjectStatus(str, Enum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class AnalysisFamily(str, Enum):
    EXPLORATORY = "EXPLORATORY"
    CAUSAL = "CAUSAL"
    PREDICTIVE = "PREDICTIVE"


class VersionedResourceStatus(str, Enum):
    DRAFT = "DRAFT"
    FIXED = "FIXED"


class AnalysisMode(str, Enum):
    EXPLORATORY = "EXPLORATORY"
    CONFIRMATORY = "CONFIRMATORY"


class StageExecutionStatus(str, Enum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    SKIPPED_DUE_TO_PREREQUISITE = "SKIPPED_DUE_TO_PREREQUISITE"
    CANCELLED = "CANCELLED"


class ResultLevel(str, Enum):
    EXECUTION_RESULT = "EXECUTION_RESULT"
    STAGE_RESULT = "STAGE_RESULT"


class ResultReuseRole(str, Enum):
    """The semantic role a canonical Result plays for a downstream consumer."""

    UPSTREAM_INPUT = "UPSTREAM_INPUT"


class ArtifactScope(str, Enum):
    SOURCE = "SOURCE"
    EXECUTION_OUTPUT = "EXECUTION_OUTPUT"


class RevisionKind(str, Enum):
    RERUN = "RERUN"
    REVISED = "REVISED"


class ArtifactType(str, Enum):
    DATASET_FILE = "DATASET_FILE"
    GRAPH_JSON = "GRAPH_JSON"
    GRAPH_IMAGE = "GRAPH_IMAGE"
    EFFECT_TABLE = "EFFECT_TABLE"
    DIAGNOSTICS_TABLE = "DIAGNOSTICS_TABLE"
    MANIFEST = "MANIFEST"
    CONFIG_SNAPSHOT = "CONFIG_SNAPSHOT"
    LOG = "LOG"
    SCIENTIFIC_RESULT_JSON = "SCIENTIFIC_RESULT_JSON"
    SCIENTIFIC_REPORT = "SCIENTIFIC_REPORT"
    CHART_SPECIFICATION = "CHART_SPECIFICATION"
    PARTITION_INDEX = "PARTITION_INDEX"
    FITTED_PREPROCESSOR = "FITTED_PREPROCESSOR"
    FITTED_MODEL = "FITTED_MODEL"
    PREDICTION = "PREDICTION"
    PREDICTIVE_EXPLANATION = "PREDICTIVE_EXPLANATION"
    MODEL_CARD = "MODEL_CARD"


class ExecutionOperation(str, Enum):
    DISCOVERY = "DISCOVERY"
    IDENTIFICATION = "IDENTIFICATION"
    ESTIMATION = "ESTIMATION"
    REFUTATION = "REFUTATION"
    SENSITIVITY = "SENSITIVITY"


class ExecutionStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class GraphVersionStatus(str, Enum):
    DRAFT = "DRAFT"
    FIXED = "FIXED"


class GraphType(str, Enum):
    DAG = "DAG"
    CPDAG = "CPDAG"
    PAG = "PAG"


class ResultType(str, Enum):
    DISCOVERY_GRAPH_RESULT = "DISCOVERY_GRAPH_RESULT"
    IDENTIFICATION_RESULT = "IDENTIFICATION_RESULT"
    DATA_ELIGIBILITY_RESULT = "DATA_ELIGIBILITY_RESULT"
    TREATMENT_EFFECT_RESULT = "TREATMENT_EFFECT_RESULT"
    DIAGNOSTICS_RESULT = "DIAGNOSTICS_RESULT"
    REFUTATION_RESULT = "REFUTATION_RESULT"
    SENSITIVITY_RESULT = "SENSITIVITY_RESULT"
    DATA_PROFILE_RESULT = "DATA_PROFILE_RESULT"
    DISTRIBUTION_RESULT = "DISTRIBUTION_RESULT"
    ASSOCIATION_RESULT = "ASSOCIATION_RESULT"
    GROUP_SUMMARY_RESULT = "GROUP_SUMMARY_RESULT"
    CHART_RESULT = "CHART_RESULT"
    SPLIT_RESULT = "SPLIT_RESULT"
    TRAINING_RESULT = "TRAINING_RESULT"
    EVALUATION_RESULT = "EVALUATION_RESULT"
    ERROR_ANALYSIS_RESULT = "ERROR_ANALYSIS_RESULT"
    PREDICTIVE_EXPLANATION_RESULT = "PREDICTIVE_EXPLANATION_RESULT"
    MODEL_CARD_RESULT = "MODEL_CARD_RESULT"


class GraphOrigin(str, Enum):
    DISCOVERED = "DISCOVERED"
    CONSTRAINT_ADJUSTED = "CONSTRAINT_ADJUSTED"
    USER_DEFINED = "USER_DEFINED"
    IMPORTED = "IMPORTED"
    USER_EDITED = "USER_EDITED"


class ScientificStatus(str, Enum):
    # Compatibility-only input value for pre-ENH-E1 adapters. Product Results
    # canonicalize it to type-specific statuses and never persist it.
    VALID = "VALID"
    GENERATED = "GENERATED"
    GENERATED_WITH_WARNINGS = "GENERATED_WITH_WARNINGS"
    UNRELIABLE = "UNRELIABLE"
    IDENTIFIED = "IDENTIFIED"
    NOT_IDENTIFIED = "NOT_IDENTIFIED"
    PARTIALLY_IDENTIFIED = "PARTIALLY_IDENTIFIED"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"
    ESTIMATED = "ESTIMATED"
    INSUFFICIENT_OVERLAP = "INSUFFICIENT_OVERLAP"
    INSUFFICIENT_SAMPLE = "INSUFFICIENT_SAMPLE"
    ESTIMATION_UNRELIABLE = "ESTIMATION_UNRELIABLE"
    NO_FAILURE_DETECTED = "NO_FAILURE_DETECTED"
    FAILURE_DETECTED = "FAILURE_DETECTED"
    INCONCLUSIVE = "INCONCLUSIVE"
    ROBUST = "ROBUST"
    FRAGILE = "FRAGILE"
    TRAINED = "TRAINED"
    TRAINED_WITH_WARNINGS = "TRAINED_WITH_WARNINGS"
    EVALUATED = "EVALUATED"
    INSUFFICIENT_TEST_SAMPLE = "INSUFFICIENT_TEST_SAMPLE"
    NOT_APPLICABLE = "NOT_APPLICABLE"
