"""Create the v1 metadata, lineage, result, and visualization schema."""

from alembic import op

from causal_atelier.infrastructure.persistence.models import Base


revision = "20260719_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # The metadata definition is the canonical initial snapshot. Future changes
    # use ordinary explicit/autogenerated Alembic operations.
    Base.metadata.create_all(bind=op.get_bind(), checkfirst=False)
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE FUNCTION causal_atelier_protect_immutable() RETURNS trigger AS $$
            BEGIN
              IF TG_TABLE_NAME = 'configuration_version'
                 AND OLD.status IN ('PUBLISHED', 'DEPRECATED')
                 AND (NEW.canonical_json, NEW.content_hash, NEW.schema_version,
                      NEW.original_format, NEW.original_text,
                      NEW.configuration_id, NEW.version_number)
                     IS DISTINCT FROM
                     (OLD.canonical_json, OLD.content_hash, OLD.schema_version,
                      OLD.original_format, OLD.original_text,
                      OLD.configuration_id, OLD.version_number) THEN
                RAISE EXCEPTION 'published configuration content is immutable';
              ELSIF TG_TABLE_NAME = 'dataset_version'
                 AND OLD.status = 'READY'
                 AND (NEW.dataset_id, NEW.version_number, NEW.source_type,
                      NEW.source_metadata, NEW.schema_hash, NEW.content_hash,
                      NEW.table_count)
                     IS DISTINCT FROM
                     (OLD.dataset_id, OLD.version_number, OLD.source_type,
                      OLD.source_metadata, OLD.schema_hash, OLD.content_hash,
                      OLD.table_count) THEN
                RAISE EXCEPTION 'ready dataset version content is immutable';
              ELSIF TG_TABLE_NAME = 'pipeline_definition_version'
                 AND OLD.status IN ('PUBLISHED', 'DEPRECATED')
                 AND (NEW.pipeline_definition_id, NEW.version_number,
                      NEW.random_seed_default, NEW.fail_fast,
                      NEW.canonical_json, NEW.content_hash)
                     IS DISTINCT FROM
                     (OLD.pipeline_definition_id, OLD.version_number,
                      OLD.random_seed_default, OLD.fail_fast,
                      OLD.canonical_json, OLD.content_hash) THEN
                RAISE EXCEPTION 'published pipeline definition version is immutable';
              ELSIF TG_TABLE_NAME = 'dataset_table_version'
                 AND (NEW.dataset_version_id, NEW.logical_name, NEW.stored_object_id,
                      NEW.ordinal, NEW.file_format, NEW.schema_json,
                      NEW.schema_hash, NEW.content_hash, NEW.partition_values)
                     IS DISTINCT FROM
                     (OLD.dataset_version_id, OLD.logical_name, OLD.stored_object_id,
                      OLD.ordinal, OLD.file_format, OLD.schema_json,
                      OLD.schema_hash, OLD.content_hash, OLD.partition_values) THEN
                RAISE EXCEPTION 'dataset table content is immutable';
              ELSIF TG_TABLE_NAME = 'artifact'
                 AND OLD.status = 'AVAILABLE'
                 AND (NEW.stored_object_id, NEW.content_hash,
                      NEW.schema_name, NEW.schema_version)
                     IS DISTINCT FROM
                     (OLD.stored_object_id, OLD.content_hash,
                      OLD.schema_name, OLD.schema_version) THEN
                RAISE EXCEPTION 'available artifact content is immutable';
              END IF;
              RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER trg_configuration_version_immutable
              BEFORE UPDATE ON configuration_version
              FOR EACH ROW EXECUTE FUNCTION causal_atelier_protect_immutable();
            CREATE TRIGGER trg_dataset_version_immutable
              BEFORE UPDATE ON dataset_version
              FOR EACH ROW EXECUTE FUNCTION causal_atelier_protect_immutable();
            CREATE TRIGGER trg_pipeline_definition_version_immutable
              BEFORE UPDATE ON pipeline_definition_version
              FOR EACH ROW EXECUTE FUNCTION causal_atelier_protect_immutable();
            CREATE TRIGGER trg_dataset_table_immutable
              BEFORE UPDATE ON dataset_table_version
              FOR EACH ROW EXECUTE FUNCTION causal_atelier_protect_immutable();
            CREATE TRIGGER trg_artifact_immutable
              BEFORE UPDATE ON artifact
              FOR EACH ROW EXECUTE FUNCTION causal_atelier_protect_immutable();

            CREATE FUNCTION causal_atelier_append_only() RETURNS trigger AS $$
            BEGIN
              RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
            END;
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER trg_run_event_append_only
              BEFORE UPDATE OR DELETE ON run_event
              FOR EACH ROW EXECUTE FUNCTION causal_atelier_append_only();
            CREATE TRIGGER trg_audit_event_append_only
              BEFORE UPDATE OR DELETE ON audit_event
              FOR EACH ROW EXECUTE FUNCTION causal_atelier_append_only();
            """
        )


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind(), checkfirst=True)
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP FUNCTION IF EXISTS causal_atelier_protect_immutable() CASCADE")
        op.execute("DROP FUNCTION IF EXISTS causal_atelier_append_only() CASCADE")
